services:
  - type: web
    name: syntax-backend
    env: node
    plan: free
    buildCommand: "NPM_CONFIG_PRODUCTION=false npm install && npm run build"
    startCommand: "npm run start:prod"
    envVars:
      - key: NODE_ENV
        value: production
        sync: false
